services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE
    ports:
      - "27017:27017"
    volumes:
      - ./database/data:/data/db
    networks:
      - tareasApp
    container_name: mongo-db

  api:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - tareasApp
    container_name: app-node

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - tareasApp
    container_name: web-client

networks:
  tareasApp:
    driver: bridge