version: '3.8'

services:
  database:
    container_name: database
    image: mongo:7.0.5
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ./database:/data/db
    networks:
      - network-despliegue
networks:
  network-despliegue:
    driver: bridge
volumes:
  database: