# Se utiliza la imagen de nginx con la versión 1.25.3 y alpine 3.18
FROM node:20.11.0-alpine3.18
# Se crea el directorio de trabajo
WORKDIR /usr/src/app
# Se copian los archivos package.json y package-lock.json al directorio de trabajo
COPY package*.json ./
# Se instalan las dependencias
RUN npm install
# Se copian todos los archivos al directorio de trabajo
COPY . .
# Se expone el puerto 3000
EXPOSE 3000
# Comando para iniciar la aplicación
CMD ["node", "index.js"]